In [1]:
import numpy as np

In [3]:
x=np.arange(1,12)

In [4]:
ak=x[:4]

In [5]:
ak

array([1, 2, 3, 4])

In [6]:
ak[:]=444

In [7]:
ak

array([444, 444, 444, 444])

In [8]:
x

array([444, 444, 444, 444,   5,   6,   7,   8,   9,  10,  11])

Görüldüğü gibi pointer mantığı gibi her 2 yerdeki değer da aynı anda değişmekte.

In [10]:
matris=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [11]:
matris[2][2]

90

In [12]:
matris[2,2]

90

In [14]:
booli=matris <50

In [15]:
matris[booli]

array([10, 20, 30, 40])

Çok güzel bir biçimde çalışıyor.

In [16]:
y=np.arange(0,10)

In [17]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
y+y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
y


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
y*y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [21]:
y**y

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [22]:
y*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.sqrt(y)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])